import { GoogleGenAI, Type } from '@google/genai';

const MODEL_NAME = 'gemini-2.5-flash';
const MAX_RETRIES = 5;
const INITIAL_RETRY_DELAY = 2000;

let keyIndex = 0;

function isCongestionError(err: unknown): boolean {
  const msg = err instanceof Error ? err.message.toLowerCase() : String(err).toLowerCase();
  return msg.includes('429') || msg.includes('too many requests') || msg.includes('resource exhausted') || msg.includes('rate_limit') || msg.includes('congestion') || msg.includes('overloaded') || msg.includes('unavailable');
}

async function withRetry<T>(fn: (key: string) => Promise<T>, apiKeys: string[]): Promise<T> {
  let lastError: unknown;
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const key = apiKeys[keyIndex % apiKeys.length];
    try {
      return await fn(key);
    } catch (err) {
      lastError = err;
      if (!isCongestionError(err)) throw err;
      // If multiple keys available, try the next one instead of waiting
      if (apiKeys.length > 1 && attempt < apiKeys.length) {
        keyIndex = (keyIndex + 1) % apiKeys.length;
        const keyNum = keyIndex + 1;
        console.log(`Key ${keyNum} congested — switching to next key (attempt ${attempt + 1})`);
        continue;
      }
      if (attempt === MAX_RETRIES - 1) throw err;
      const delay = INITIAL_RETRY_DELAY * Math.pow(2, attempt) + Math.random() * 1000;
      console.log(`Model congested — retrying in ${(delay / 1000).toFixed(1)}s (attempt ${attempt + 1}/${MAX_RETRIES})…`);
      await new Promise(resolve => setTimeout(resolve, delay));
    }
  }
  throw lastError;
}

function createAI(apiKey: string) {
  return new GoogleGenAI({ apiKey });
}

async function draftArticleContent(
  ai: GoogleGenAI,
  topic: string,
  keywords: string[]
): Promise<string> {
  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: `Write a comprehensive, exhaustive long-form essay on this topic:

Topic: "${topic}"
Target Keywords to distribute organically (do not force or stuff): ${keywords.join(', ')}

CRITICAL WRITING INSTRUCTIONS:
- Write with extreme depth and specificity. No fluff, no meta-commentary, no introductory filler phrases.
- DO NOT use these banned phrases: "In today's digital landscape", "delve", "testament", "crucial", "paramount", "multifaceted", "tapestry", "in conclusion", "furthermore", "in today's fast-paced world", "it is worth noting", "it goes without saying"
- Every claim must be backed by concrete logic, named examples, or verifiable patterns — not vague generalities
- Vary sentence lengths aggressively. Follow a complex, technical sentence with a three-word punch. Like this.
- Use em-dashes for asides — the way a real writer would
- Start some sentences with "And" or "But" — it is not wrong, it is human
- Include specific numbers, percentages, and named case studies where appropriate
- Format in standard Markdown: ## headings, **bold** for key terms, bullet lists, blockquotes for notable quotes
- Write like a senior expert speaking to a respected peer over coffee — confident, slightly opinionated, allergic to corporate fluff
- Minimum 1,500 words. Aim for 2,000-2,500 words for maximum depth.`,
    config: {
      systemInstruction: `You are an elite subject-matter expert, technical journalist, and former editor at a major technology publication. Your writing is authoritative, precise, and direct. You prioritize verified data, logical mechanics, and actionable insights. You have a distinctive voice — thoughtful, occasionally dry in its wit, never condescending. You write for readers who are intelligent and time-poor, and who will immediately close a tab at the first sign of padding or cliché.`,
      temperature: 0.75,
    },
  });
  return response.text ?? '';
}

async function runAuthenticityCheck(
  ai: GoogleGenAI,
  draft: string
): Promise<{ passedCheck: boolean; score: number; vulnerabilities: string[]; suggestions: string[] }> {
  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: `Analyze the following article draft for authenticity, factual vulnerabilities, logical errors, and AI-generated writing patterns:

---
${draft.slice(0, 8000)}
---

Evaluate rigorously for:
1. Absolute statistical claims that appear fabricated or unverifiable
2. Logical leaps or unsupported generalizations
3. Hallucinated product names, company names, or study attributions
4. Robotic sentence patterns, repetitive transitions, or AI clichés
5. Claims that contradict established expert consensus
6. Missing nuance or oversimplification of complex topics`,
    config: {
      systemInstruction: `You are a cynical, meticulous fact-checker and senior editor for a major scientific and technology publication. Your job is to find every weak argument, every logical leap, every unverified absolute statistic, and every statement that sounds like it was generated by an AI without genuine knowledge. You are known for your zero-tolerance policy toward vague generalities and fabricated data. You are not trying to rewrite the article — only to identify every specific flaw so another editor can fix them.`,
      temperature: 0.1,
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          passedCheck: {
            type: Type.BOOLEAN,
            description: 'True if the article contains no flagrant logical errors, unverified absolute statistics, or hallucinated references.',
          },
          score: {
            type: Type.INTEGER,
            description: 'Overall authenticity and quality score from 1 to 100. 90+ is ready to publish. 75-89 needs minor polish. Below 75 needs significant rework.',
          },
          vulnerabilities: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: 'Specific sentences or phrases that contain absolute claims, logical weaknesses, or potential hallucinations. Quote directly from the text.',
          },
          suggestions: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: 'Specific, actionable adjustments to make the content completely factual and robust. One suggestion per vulnerability.',
          },
        },
        required: ['passedCheck', 'score', 'vulnerabilities', 'suggestions'],
      },
    },
  });

  try {
    return JSON.parse(response.text ?? '{}');
  } catch {
    return {
      passedCheck: false,
      score: 60,
      vulnerabilities: ['Could not parse audit response.'],
      suggestions: ['Manual review recommended.'],
    };
  }
}

async function optimizeAndPolish(
  ai: GoogleGenAI,
  draft: string,
  auditResults: { suggestions: string[] }
): Promise<string> {
  const suggestionsText = auditResults.suggestions.length > 0
    ? `Address these specific issues:\n${auditResults.suggestions.map((s, i) => `${i + 1}. ${s}`).join('\n')}`
    : 'Refine for maximum clarity and human cadence.';

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: `Revise and polish this article to eliminate all AI-generated writing patterns and fix any factual vulnerabilities.

${suggestionsText}

ORIGINAL DRAFT:
${draft}

REVISION MANDATE:
1. Vary sentence lengths aggressively — mix 40-word compound sentences with three-word punches
2. Remove ALL banned words: delve, testament, digital landscape, paramount, crucial, multifaceted, tapestry, in conclusion, furthermore, it is worth noting
3. Replace vague statistics with hedged, honest language: instead of "studies show 80% of companies...", write "most engineering teams that have measured this..."
4. Inject micro-imperfections: conversational asides, the occasional em-dash thought, sentences that start with And or But
5. Every paragraph should advance the reader's understanding — delete anything that merely restates what was just said
6. Maintain all Markdown formatting (##, ###, **bold**, lists, blockquotes)
7. Preserve all specific examples, named companies, and concrete data points — only improve the framing
8. The final article should read like it was written by a human expert who has genuine opinions on this topic`,
    config: {
      systemInstruction: `You are a master copyeditor and essayist who specializes in humanizing and elevating technical prose. You have an exceptional ear for rhythm and cadence. You strip away corporate jargon, eliminate robotic sentence structures, and inject clarity, personality, and precision into every paragraph. Your edited work consistently passes AI-detection systems not by gaming them, but because the underlying prose is genuinely human in its construction — varied, opinionated, and specific. You never make the content shorter; you make every word earn its place.`,
      temperature: 0.55,
    },
  });
  return response.text ?? draft;
}

function availableKeys(primaryKey: string, key2: string, key3: string): string[] {
  const keys = [primaryKey];
  if (key2) keys.push(key2);
  if (key3) keys.push(key3);
  return keys;
}

export async function executePipeline(
  topic: string,
  keywords: string[],
  primaryKey: string,
  key2 = '',
  key3 = ''
): Promise<{
  status: 'ready_to_publish' | 'quarantined' | 'error';
  title: string;
  content: string;
  audit?: { passedCheck: boolean; score: number; vulnerabilities: string[]; suggestions: string[] };
  reason?: string;
  excerpt?: string;
  tags?: string[];
  isApproved?: boolean;
}> {
  const apiKeys = availableKeys(primaryKey, key2, key3);

  try {
    const rawDraft = await withRetry(
      (k) => draftArticleContent(createAI(k), topic, keywords),
      apiKeys
    );
    const auditResults = await withRetry(
      (k) => runAuthenticityCheck(createAI(k), rawDraft),
      apiKeys
    );

    if (auditResults.score < 65) {
      return {
        status: 'quarantined',
        title: topic,
        content: rawDraft,
        audit: auditResults,
        reason: `Authenticity score ${auditResults.score}/100 is below the 65-point minimum threshold. Routed to manual review.`,
        excerpt: rawDraft.slice(0, 160).replace(/[#*]/g, '').trim(),
        tags: keywords.slice(0, 4),
      };
    }

    const polishedContent = await withRetry(
      (k) => optimizeAndPolish(createAI(k), rawDraft, auditResults),
      apiKeys
    );

    return {
      status: 'ready_to_publish',
      title: topic,
      content: polishedContent,
      audit: auditResults,
      excerpt: polishedContent.slice(0, 160).replace(/[#*]/g, '').trim(),
      tags: keywords.slice(0, 4),
      isApproved: true,
    };
  } catch (error: unknown) {
    const errMsg = error instanceof Error ? error.message : String(error);
    return {
      status: 'error',
      title: topic,
      content: '',
      reason: errMsg,
    };
  }
}

export async function validateContent(
  content: string,
  primaryKey: string,
  key2 = '',
  key3 = ''
): Promise<{ passedCheck: boolean; score: number; vulnerabilities: string[]; suggestions: string[] }> {
  const apiKeys = availableKeys(primaryKey, key2, key3);
  return withRetry(
    (k) => runAuthenticityCheck(createAI(k), content),
    apiKeys
  );
}
